spring.application.name=springdata
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_data_jpa
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.session.jdbc.initialize-schema=always

# springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

jwt.secret = YnJ1bm9fc3ByaW5nX2Jvb3RfdGVzdF9rZXlfMjU2X2JpdHNfc2VjdXJl
jwt.expiration = 86400000
