spring.datasource.url=jdbc:postgresql://db-server-prod.domeniul-tau.com:5432/proddb
spring.datasource.username=prod_admin
spring.datasource.password=ParolaSuperSigura123!
spring.datasource.driver-class-name=org.postgresql.Driver